### ISSUE TITLE
Search param is `nil` in odd cases of search method.

### ISSUE THREAD

**Issue by joshuapinter** [nathanl/searchlight#29]
This is an odd one. 

Here is my Search class: 

````ruby
class ToDoSearch < Searchlight::Search

  search_on ToDo.scoped

  searches :state

  def search_state
    debugger                  # state == 'due_soon'
    # state = state.to_sym
    search.send( state )
  end

end
````

 Now, when I uncomment `state = state.to_sym` and hit the debugger the value of `state` becomes `nil`. Nothing else is changed. 

````ruby
def search_state
  debugger                    # state == nil
  state = state.to_sym
  search.send( state )
end
````

Why do you think that is? Does `search` somehow need to be the first thing in the method?

Thanks!

**Comment by joshuapinter** [comment]
I ended up doing the following to get around it but I'm still curious as to what's happening here and why? 

````ruby
def search_state
  search.send( state )
end

def state
  super.to_sym
end
````

**Comment by nathanl** [comment]
If I'm understanding correctly, you're doing something a little unusual with your search and also maybe hitting a quirk of Ruby. :) The search is expecting you to pass an option called `state` and to initialize the value that way.

As for the nil, I think you can see something similar if you create a small program.

```ruby
stuff = "hi" if false
puts stuff.inspect
```

If you run this, Ruby will tell you that stuff is nil. If you comment the first line, it will complain that stuff is undefined. What gives? It shouldn't define it because `if false` is always false, right? But Ruby decides what variables exist before it decides what logic branches will execute. So I think your assignment was triggering that.

**Comment by joshuapinter** [comment]
Hi @nathanl. Thanks for the response! And thanks for the gem!

Your example makes perfect sense but I'm not doing anything like that. I'm literally just passing a string for `state` as a search param. The only thing I'm trying to do is convert the string to a symbol. No conditionals are being used and no "funny business". :)

Any other ideas?

Thanks.

**Comment by nathanl** [comment]
@joshuapinter I haven't forgotten this, I just haven't found time to investigate yet. :)

**Comment by nathanl** [comment]
OK, well after I said that, I got too curious and investigated. :smile: I was basically right: this is Ruby weirdness, not Searchlight weirdness.

Here's a little script with comments to explain what's going on.

```ruby
class Example

  attr_accessor :property

  def initialize(property_value)
    self.property = property_value
  end

  # This version raises "undefined method `to_sym` for nil:NilClass
  def version_1
    # Ruby sees the `property = ` and creates a local variable by
    # that name. It starts out nil.
    # When we call `property.to_sym`, we're getting the local variable,
    # not the method. Our local variable has overshadowed the method.
    property = property.to_sym
    puts property
  end

  # This version works fine, but is hacky
  def version_2
    # Here we dance around the problem by calling the method before we
    # define a local variable that overshadows it
    p = property
    property = p
    puts property
  end

  # This version works fine - more sensible
  def version_3
    # Here we disambiguate by explicitly saying "send this message to self (call the method)"
    property = self.property.to_sym
    puts property
  end

end

puts "\ntrying version 3"
Example.new("greetings, planet").version_3

puts "\ntrying version 2"
Example.new("greetings, planet").version_2

puts "\ntrying version 1"
Example.new("greetings, planet").version_1
```

But as it turns out, in your case, you don't have to do any of these workarounds. You're calling `state` so that you can get the string, so that you can call `.to_sym`, so that you can use it in `send()`, right? But `send` will happily accept a string. :smile:

```ruby
"bonanza".send(:upcase)  #=> "BONANZA"
"bonanza".send("upcase") #=> "BONANZA"
```

So all you need is:

```ruby
def search_state
  search.send( state )
end
```

**Comment by joshuapinter** [comment]
Bravo!! :clap: 

This would make a great blog post!

Thanks for going through this. I just assumed there was some magic going on with Searchlight that I wasn't aware of so I'm glad you tracked it down because I learned something important with Ruby and variable/method scoping.

For the record, the main reason I was doing `.to_sym` was to whitelist the param value before passing it to `.send`, like so: 

```ruby
def search_state
  state_symbol = self.state.to_sym

  raise 'Unknown state.' unless WHITELIST_STATES.include?( state_symbol )
    
  search.send( state )
end
```

Alright, mystery solved! Thanks again!

Josh

**Comment by nathanl** [comment]
@joshuapinter What, too scared to just call whatever method some random user types in? :laughing: Your whitelist makes lots of sense.

We learned something today - yay! The More You Know - :rainbow:

**Comment by joshuapinter** [comment]
![thumbs-up](https://cloud.githubusercontent.com/assets/180819/7326082/fbf7d220-ea7f-11e4-872e-e9823b6ac1b5.gif)
